/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app.index'
import { Route as AppWorksImport } from './routes/_app.works'
import { Route as AppAdminWorksImport } from './routes/_app.admin.works'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppWorksRoute = AppWorksImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => AppRoute,
} as any)

const AppAdminWorksRoute = AppAdminWorksImport.update({
  id: '/admin/works',
  path: '/admin/works',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/works': {
      id: '/_app/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof AppWorksImport
      parentRoute: typeof AppImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/admin/works': {
      id: '/_app/admin/works'
      path: '/admin/works'
      fullPath: '/admin/works'
      preLoaderRoute: typeof AppAdminWorksImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppWorksRoute: typeof AppWorksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminWorksRoute: typeof AppAdminWorksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorksRoute: AppWorksRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminWorksRoute: AppAdminWorksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/works': typeof AppWorksRoute
  '/': typeof AppIndexRoute
  '/admin/works': typeof AppAdminWorksRoute
}

export interface FileRoutesByTo {
  '/works': typeof AppWorksRoute
  '/': typeof AppIndexRoute
  '/admin/works': typeof AppAdminWorksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/works': typeof AppWorksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/works': typeof AppAdminWorksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/works' | '/' | '/admin/works'
  fileRoutesByTo: FileRoutesByTo
  to: '/works' | '/' | '/admin/works'
  id: '__root__' | '/_app' | '/_app/works' | '/_app/' | '/_app/admin/works'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/works",
        "/_app/",
        "/_app/admin/works"
      ]
    },
    "/_app/works": {
      "filePath": "_app.works.tsx",
      "parent": "/_app"
    },
    "/_app/": {
      "filePath": "_app.index.tsx",
      "parent": "/_app"
    },
    "/_app/admin/works": {
      "filePath": "_app.admin.works.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
